setA = set([1, 2, 3, 4])
setB = set([3, 4, 5, 6])
u = setA.union(setB)
i = setA.intersection(setB)
#print("Union:", u)
#print("Intersection:", i)
#print(f'{u=}')
#print(f'{i=}')
print(f"{u}")
print(f"{i}")
